config/routes.rb
Eshop::Application.routes.draw do

  resources :posts, only: [:index, :show]

  namespace :admin do
    resources :posts, except: [:show, :destroy]
    resources :products, except: [:show, :destroy]
  end

  get "/kontakt" => "pages#contact", as: :contact

  root to: "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base

  scope :published, -> { where(published: true) }

end

app/models/product.rb
class Product < ActiveRecord::Base

  scope :published, -> { where(published: true) }

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new params[:post].permit(:title, :body, :published)

    if @post.save
      redirect_to admin_posts_url
    else
      render :new
    end
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]

    if @post.update params[:post].permit(:title, :body, :published)
      redirect_to admin_posts_url
    else
      render :edit
    end

  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @post = Product.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def contact
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.published
  end

  def show
    @post = Post.published.find params[:id]
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post] do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control ckeditor", rows: 10 %>
  </div>

  <div class="form-group">
    <%= f.check_box :published %>
    <%= f.label :published %>
  </div>

  <%= f.submit "Uložiť článok", class: "btn btn-primary" %>

<% end %>

app/views/admin/posts/edit.html.erb
<h1>Upraviť článok</h1>

<%= render "form" %>

app/views/admin/posts/index.html.erb
<h1>Admin článkov</h1>

<p>
  <%= link_to "Pridať článok", new_admin_post_path, class: "btn btn-primary" %>
</p>

<table class="table">

  <thead>
    <tr>
      <th>Nazov</th>
      <th>Publikovane</th>
      <th>Akcie</th>
    </tr>
  </thead>

  <tbody>

    <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.published %></td>
      <td><%= link_to "Upravit", edit_admin_post_path(post) %></td>
    </tr>
    <% end %>

  </tbody>
</table>

app/views/admin/posts/new.html.erb
<h1>Nový článok</h1>

<%= render "form" %>

app/views/admin/products/_product_form.html.erb
<%= product_form_for [:admin, @product] do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control ckeditor", rows: 10 %>
  </div>

  <div class="form-group">
    <%= f.check_box :published %>
    <%= f.label :published %>
  </div>

  <%= f.submit "Uložiť článok", class: "btn btn-primary" %>

<% end %>

app/views/admin/products/edit.html.erb
<h1>Upraviť produkt</h1>

<%= render "product_form" %>

app/views/admin/products/index.html.erb
<h1>Admin produktov</h1>

<p>
  <%= link_to "Pridať produkt", new_admin_product_path, class: "btn btn-primary" %>
</p>

<table class="table">

  <thead>
    <tr>
      <th>Nazov</th>
      <th>Popis</th>
      <th>cena</th>
    </tr>
  </thead>

  <tbody>

    <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.describtion %></td>
      <td><%= product.price %></td>
      <td><%= product.published %></td>
      <td><%= link_to "Upravit", edit_admin_product_path(product) %></td>
    </tr>
    <% end %>

  </tbody>
</table>

app/views/admin/products/new.html.erb
<h1>Nový produkt</h1>

<%= render "product_form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eshop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
  <div class="container">
    <ul class="nav nav-pills">
      <li class="active"><%= link_to "Home", "#" %></li>
      <li><%= link_to "Blog", posts_path %></li>
      <li><%= link_to "Kontakt", contact_path %></li>
    </ul>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pages/contact.html.erb
<h1>Kontakt</h1>

<p>Adresa: The Spot</p>
<p>Tel: 0901 123 123</p>

app/views/posts/index.html.erb
<h1>Články</h1>

<% @posts.each do |post| %>
  <h3><%= link_to post.title, post_path(post) %></h3>

  <p><%= post.body %></p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<%= @post.body.html_safe %>